---
new_page_extension: md
auto_deploy: false
admin_path: forestry_admin
webhook_url: 
sections:
- type: directory
  path: static/css
  label: css
  create: all
  match: "**/*"
- type: directory
  path: layouts/partials
  label: everything
  create: none
  match: "**/*"
  templates:
  - classes-html-template
- type: directory
  path: content/layouts
  label: layouts
  create: all
  match: "**/*"
- type: directory
  path: data
  label: Data
  create: none
  match: "**/*"
  new_doc_ext: yml
  templates:
  - board
  - classes
  - contact
  - faq
  - teacher
  - testimonial
  - tradition
  - school
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  templates:
  - blog-post
upload_dir: static/images/blog
public_path: static/images/blog
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
version: 0.55.6
